[general]
import = ["~/.config/alacritty/themes/themes/carbonfox.toml"]

[window]
decorations = "buttonless"
opacity = 0.95
option_as_alt = "Both"
padding = { x = 8, y = 8 }

[font]
size = 20.0

[font.normal]
family = "VictorMono Nerd Font"

[terminal]
shell = "/bin/zsh"
